### ISSUE TITLE
I have problem with connect.

### ISSUE THREAD

**Issue by sythuan92** [akasakaid/metabos#3]
It show on my terminal
Traceback (most recent call last):
  File "c:\Users\IN BRAND\Downloads\metabos-main\metabos-main\botv1.py", line 183, in <module>
    MetaBossBot().main()
  File "c:\Users\IN BRAND\Downloads\metabos-main\metabos-main\botv1.py", line 81, in main
    ws.connect("wss://api.metaboss.xyz:2000/game", timeout=10)
  File "C:\Users\IN BRAND\AppData\Roaming\Python\Python310\site-packages\websocket\_core.py", line 256, in connect
    self.sock, addrs = connect(
  File "C:\Users\IN BRAND\AppData\Roaming\Python\Python310\site-packages\websocket\_http.py", line 145, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "C:\Users\IN BRAND\AppData\Roaming\Python\Python310\site-packages\websocket\_http.py", line 232, in _open_socket
    raise err
  File "C:\Users\IN BRAND\AppData\Roaming\Python\Python310\site-packages\websocket\_http.py", line 209, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by akasakaid** [comment]
> It show on my terminal
> Traceback (most recent call last):
>   File "c:\Users\IN BRAND\Downloads\metabos-main\metabos-main\botv1.py", line 183, in <module>
>     MetaBossBot().main()
>   File "c:\Users\IN BRAND\Downloads\metabos-main\metabos-main\botv1.py", line 81, in main
>     ws.connect("wss://api.metaboss.xyz:2000/game", timeout=10)
>   File "C:\Users\IN BRAND\AppData\Roaming\Python\Python310\site-packages\websocket\_core.py", line 256, in connect
>     self.sock, addrs = connect(
>   File "C:\Users\IN BRAND\AppData\Roaming\Python\Python310\site-packages\websocket\_http.py", line 145, in connect
>     sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
>   File "C:\Users\IN BRAND\AppData\Roaming\Python\Python310\site-packages\websocket\_http.py", line 232, in _open_socket
>     raise err
>   File "C:\Users\IN BRAND\AppData\Roaming\Python\Python310\site-packages\websocket\_http.py", line 209, in _open_socket
>     sock.connect(address)
> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Yeah, maybe need some update
